name: PHP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Start PHP server
        run: php -S 0.0.0.0:8000 bst.php &

      - name: Wait for server to start
        run: sleep 10

      - name: Test server
        run: curl http://localhost:8000?id=165
